### PR TITLE
outFilter option

### PR DESCRIPTION
**Pull request by john9x**
Added outFilter option to apply ProGuard filters to output jar.

### CODE REVIEW

**Comment by cmorty** [comment]
Looks ok to me (didn't test).

**Comment by john9x** [comment]
So...what's next? Can you merge it and release it?

**Comment by cmorty** [comment]
Sorry, this is a pure background project. @wvengen Do you have time to realesa?

**Comment by john9x** [comment]
No problem. Thanks!

**Comment by wvengen** [comment]
I'll put releasing it on my todo list. Thanks!

**Pull request merged**
