### PR TITLE
Adding the option to specify the mapping and seed file in the POM configuration

### PR DESCRIPTION
**Pull request by kristofmoens**
I changed the ProguardMojo.java to be able to change the names of the seeds and mapping filename. It should default to the previous filenames.

### CODE REVIEW

**Comment by wvengen** [comment]
Thanks for the contribution! It looks good, could anyone test this and report?

Does this parameter end up in the documentation? It should certainly be listed in the [goal documentation](http://wvengen.github.io/proguard-maven-plugin/proguard-mojo.html), and perhaps also on the [introduction page](http://wvengen.github.io/proguard-maven-plugin/).

**Comment by kristofmoens** [comment]
I changed the documentation a bit, adding the map and seed file.

When I generate the documentation the new parameters are there, but they don't show up on your github.io page? Don't know about when the synchronisation is done.

**Comment by cmorty** [comment]
@wvengen This seems simple enaugh to just merge and wait until someone complains. ;)
@kristofmoens ?! The github.io-pages must be updated by @wvengen

**Comment by kristofmoens** [comment]
Ok, I will close the commit. :-)

**Comment by wvengen** [comment]
Ok, let's merge it then.
Documentation will be updated automatically by Travis CI when merged. By closing, do you mean to retract the contribution? Please reopen so that we can merge when you'd like it to.

**Comment by kristofmoens** [comment]
Oops sorry.

**Comment by kristofmoens** [comment]
I thought because it was taking that long to merge, I needed to close it. Done :-)

**Comment by wvengen** [comment]
Thanks! I'll try to do a release soon.

**Comment by wvengen** [comment]
Released on Maven Central, version 2.0.11.

**Comment by kristofmoens** [comment]
I suppose the use of relative paths in the configuration of the plugin are by design? So it would be difficult to write outside of the Maven dir? This design decision makes it a bit more difficult to centralize the mapping files.

Maybe if there is a need for a feature, I could make a modification; any suggestions of possible additions? Like deploying the mapping file to the central server in a different jar, ...?

**Comment by wvengen** [comment]
I'd suppose that when you want to centralize the mapping files, you'd add an additional build step using a different maven plugin to put them in the correct place. That way this plugin wouldn't need to know all kinds of upload mechanisms.
What do you think?

**Comment by kristofmoens** [comment]
You're right that the uploading should be left to a different plugin. I was thinking about being able to create a separate jar containing the mapping and seed files, so they could be pushed to somewhere else (by another plugin), so they are more easy to centralize with the obfuscated jars in a central repo. So in your repo you would have something like app-1.0.1-SNAPSHOT and app-seeds-1.0.1-SNAPSHOT, so they can be easier managed. But that's maybe not too useful, I guess. ;-)

**Comment by kristofmoens** [comment]
Thanks for the reply. :-)

**Comment by dirk-olmes** [comment]
@kristofmoens I use an ant plugin to copy the file to a different location as part of my build. 

You could use the archetype plugin to pack a zip/jar containing the seeds and attach that artifact to the build so it's installed into the repository along with the main artifact.

I'm not a fan of complicating the proguard plugin with this kind of features, though.

**Pull request merged**
