### PR TITLE
Made possible to silence proguard output

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by wvengen** [comment]
Thanks for your contribution! Looking good.
Do we need to update docs, or does the docstring end up there clearly enough?
If anyone can test and confirm if this works (I guess so, but just to be sure), I'll be happy to merge.

**Comment by velo** [comment]
Well, I did =D

I guess it's enough, I copy from some other maven plugin that has the silent treatment option.

**Comment by wvengen** [comment]
Thanks!
And indeed, _silent_ is [present](http://wvengen.github.io/proguard-maven-plugin/proguard-mojo.html) in the generated documentation.

**Comment by velo** [comment]
Nice, any idea when a new release will be available?

**Comment by wvengen** [comment]
Just published and uploaded to maven central, thanks for reminding me ;)

**Pull request merged**
