### PR TITLE
Preserve manifest file

### PR DESCRIPTION
**Pull request by Bartimmermans**
#211 allow to preserve the manifest file

### CODE REVIEW

**Comment by lasselindqvist** [comment]
Thanks. How was this tested?

**Comment by Bartimmermans** [comment]
It has been (manually) tested in an actual project build.

**Comment by Bartimmermans** [comment]
Thanks for the merge. Looking forward to the next release!

**Comment by Bartimmermans** [comment]
@lasselindqvist Any foreseen date for the next release that includes this feature?

**Comment by lasselindqvist** [comment]
https://github.com/wvengen/proguard-maven-plugin/commits/master
I think this should be in 2.6.0. Can you confirm?

**Comment by Bartimmermans** [comment]
It seems to be in 2.6.0 indeed. Sorry, I couldn't find that release on the release page https://github.com/wvengen/proguard-maven-plugin/releases.

**Pull request merged**
