### PR TITLE
Support attaching map and seed files as artifacts

### PR DESCRIPTION
**Pull request by mdaniel**
Another 1/7th of #32

### CODE REVIEW

**Comment by cmorty** [comment]
I'm not familiar enough with this stuff (pretty stupid when maintaining a plugin, hugh?). How much trouble is it to create a test-case. We have to few of them anyway. ;)

**Comment by mdaniel** [comment]
I wouldn't say it's terrible, but I had to stop because the minutes invested in a test case wouldn't pay immediate dividends for the situation I was in. It only took a few seconds to run the build with the "map" and "seed" options enabled (respectively), but automating that is a lot of typing.

I can _try_ to put something together for it if that is a prerequisite for this landing, but based on your strong desire for isolated PRs, now _that_ seems like it should be in its own PR

**Comment by cmorty** [comment]
As there are no real regression tests as of now, I can live without one. But if you do have time to write one, that would be awesome. Even at a later point of time. If nobody complains, I'll do an optimistic merge. :)
As for the PRs: It should always be one feature per PR. And the regression test would be part of the feature - put into a separate commit. The advantage is, that certain things can be merged while waiting for others to be fixed.

**Comment by cmorty** [comment]
Seems like my merges require a rebase.

**Comment by cmorty** [comment]
@mdaniel Can you rebase this. Once it's merged, I think we can push a new version.

**Comment by mdaniel** [comment]
I have done so; sorry for the delay, we had a massive push at work. I also have a hello-world of an integration test that I'll PR separately.

**Comment by cmorty** [comment]
No problem. I often loose things out of focus, and a little little reminder can help. :)

**Comment by cmorty** [comment]
@wvengen I think we can make a release. I'd postpone merging #40 to after the release.

**Pull request merged**
