### PR TITLE
.gitignore update with entries generated from Eclipse.

### PR DESCRIPTION
**Pull request by rmrodrigues**
proguard.skip JVM property handler added.

### CODE REVIEW

**Comment by FibreFoX** [comment]
This is ment to fix #52 right? Would you mind to take the time to create some [mcve](http://stackoverflow.com/help/mcve) first? Maybe there is a different fix. If the skip-property isn't picked up correctly, this might not be some proper fix for this. Maven-plugins usually should work as expected, without the need to check JVM properties.

**Comment by rmrodrigues** [comment]
Yes,it is.
I've tried with another project and I'm not being able to solve this problem.

**Comment by rmrodrigues** [comment]
I've figured out the problem.
If I have  **<skip>false<skip>** on pom.xml, the **-Dproguard.skip** is ignored.
So, I this the skip property must be overwritten by JVM properties, in this case.

What do you think? If you agree, you can accept my pull request because it solves this question.
Thanks.

**Comment by FibreFoX** [comment]
Do you have this?
```xml
<properties>
<proguard.skip>false</proguard.skip>
</properties>
```
Or did you have `<skip>false</skip>`?

Personally, if it's the later one, I would tend to not accept this PR, because the maven configuration is still wrong. And to make it worse, it isn't really visible enough to the readers of the `pom.xml`.

If Mojo-properties are existing, they should be used. Especially with multiple executions ;) imagine the situation where the project-setup chooses which execution should run, you would end up wondering whats happening.

**Comment by rmrodrigues** [comment]
Hi,
I've the last one. <skip>false</skip>. You are right. Decline the PR.
Thanks.

**Pull request closed without merging**
